# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moving',
            name='fine_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moving',
            name='location_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
