# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20160419_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='moving',
            name='when',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
