# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_moving_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
            ],
        ),
    ]
