# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_agency_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moving',
            name='paid_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
