# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20160419_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='moving',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo')], default=None, max_length=16),
            preserve_default=False,
        ),
    ]
