# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0007_moving_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moving',
            name='accident',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moving',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('moving', 'Moving'), ('mover void', 'Mover Void'), ('no ticket type', 'No Ticket Type')], max_length=16),
        ),
    ]
